spring.application.name=pfa-backend

server.port=${PORT:8080}
server.address=0.0.0.0

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.connection-timeout=10000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC


app.cors.allowedOrigins=http://localhost:*,http://127.0.0.1:*,https://frontend-for-finance.vercel.app
