spring.application.name=pfa-backend

server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.h2.console.enabled=true
spring.h2.console.path=/h2

app.cors.allowedOrigins=http://localhost:*,http://127.0.0.1:*
